### ISSUE TITLE
Idea: Add a sound for each type of event

### ISSUE THREAD

**Issue by thgcode** [josephsl/evtTracker#1]
I thought of this idea, this might help if an app does some event consistently and you can not view the log for some reason (NVDA crashes for example), or if you want to have an idea of what evvents occurred and look for a specific one on the log.

**Comment by josephsl** [comment]
Hi, I see. Thanks.

**Comment by josephsl** [comment]
Hi,

Note that sometimes the sound playback functionality inside NVDA may crash as well or NVDA may get confused as to which sound playback device is active.

Another important note: Event Tracker is in maintenance mode, so I don't expect to add or accept new features. I think there is a possibility that NVDA may include much improved events tracing functionality, and if that happens, I plan to discontinue this add-on.

Thanks.
